import { defineConfig } from 'bunup'
import { unused } from 'bunup/plugins'

export default defineConfig({
  plugins: [unused()],
  entry: ['src/index.ts'],
  format: ['esm'],
  outDir: 'dist',
  minify: true,
  clean: true,
  sourcemap: true,
  platform: 'browser',
  external: [
    'react',
    'react-dom',
    // Externalize all Node.js built-ins
    'node:module',
    'node:fs',
    'node:path',
    'node:url',
    'node:util',
    'node:stream',
    'node:buffer',
    'node:events',
    'node:crypto',
    'node:os',
    'node:process',
    'node:http',
    'node:https',
    'node:net',
    'node:tls',
    'node:dns',
    'node:zlib',
    'node:querystring',
    'node:child_process',
    'node:cluster',
    'node:worker_threads',
    // Also externalize without 'node:' prefix (for compatibility)
    'module',
    'fs',
    'path',
    'url',
    'util',
    'stream',
    'buffer',
    'events',
    'crypto',
    'os',
    'process',
    'http',
    'https',
    'net',
    'tls',
    'dns',
    'zlib',
    'querystring',
    'child_process',
    'cluster',
    'worker_threads',
  ],
})
